#!/bin/sh 
curl -S -F "image=@$1" -F "key=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" http://api.imgur.com/2/upload.xml>/tmp/~ret
org=$(sed -n -e 's#.*<original>\(.*\)</original>.*#\1#' -e '2p' /tmp/~ret)
pre=$(sed -n -e 's#.*<small_square>\(.*\)</small_square>.*#\1#' -e '2p' /tmp/~ret)
echo "[URL=${org}][IMG]${pre}[/IMG][/URL]"|xclip -selection clipboard
if [[ -z "$org" ]]; then
	org="???"
fi
if [[ -z "$pre" ]]; then
	pre="???"
fi
zenity --info --title="Imgur Upload" --text="Originalaus dydžio: ${org}\nPeržiūra: ${pre}" --height=50
